Cargo.lock, Cargo.toml, shapely-core/CHANGELOG.md, shapely-derive/CHANGELOG.md, shapely-json/CHANGELOG.md, shapely-yaml/CHANGELOG.md, shapely/CHANGELOG.md
* `shapely-core`: 1.0.0 -> 2.0.0 (⚠ API breaking changes)
* `shapely-derive`: 1.0.0 -> 2.0.0
* `shapely`: 1.0.0 -> 2.0.0 (⚠ API breaking changes)
* `shapely-json`: 1.0.0 -> 2.0.0 (✓ API compatible changes)
* `shapely-yaml`: 1.0.0 -> 2.0.0
```text
--- failure enum_missing: pub enum removed or renamed ---
Description:
A publicly-visible enum cannot be imported by its prior path. A `pub use` may have been removed, or the enum itself may have been renamed or removed entirely.
ref: https://doc.rust-lang.org/cargo/reference/semver.html#item-remove
impl: https://github.com/obi1kenobi/cargo-semver-checks/tree/v0.39.0/src/lints/enum_missing.ron
Failed in:
enum shapely_core::InitFieldSlot, previously in file /tmp/.tmpnGMAun/shapely-core/src/partial.rs:345
--- failure …
```
=> chore: release v2.0.0

Cargo.lock, Cargo.toml, shapely-core/CHANGELOG.md, shapely-pretty/CHANGELOG.md, shapely/CHANGELOG.md
* `shapely-core`: 2.0.1 -> 3.0.0 (⚠ API breaking changes)
* `shapely-derive`: 2.0.1 -> 3.0.0
* `shapely`: 2.0.1 -> 3.0.0 (✓ API compatible changes)
* `shapely-json`: 2.0.1 -> 3.0.0
* `shapely-msgpack`: 2.0.1 -> 3.0.0
* `shapely-pretty`: 2.0.1 -> 3.0.0
* `shapely-urlencoded`: 2.0.1 -> 3.0.0
* `shapely-yaml`: 2.0.1 -> 3.0.0
```text
--- failure constructible_struct_adds_field: externally-constructible struct adds field ---
Description:
A pub struct constructible with a struct literal has a new pub field. Existing struct literals must be updated to include the new field.
ref: https://doc.rust-lang.org/reference/expressions/struct-expr.html
impl: https://github.com/obi1kenobi/cargo-semver-checks/tree/v0.39.0/src/lints/constructible_struct_adds_field.ron
Failed in:
field Field.flags in …
```
=> chore: release v3.0.0

shapely-codegen/src/main.rs, shapely-core/src/tuples_impls.rs
Const contexts _do_ have access to outer generics :)
https://bsky.app/profile/lukaswirth.bsky.social/post/3lloofn4tfk2d
=> Use trick by @veykril to reduce codegen size

Cargo.lock, Cargo.toml, shapely-codegen/CHANGELOG.md, shapely-derive/CHANGELOG.md, shapely-json/CHANGELOG.md, shapely-json/Cargo.toml, shapely-opaque/CHANGELOG.md, shapely-peek/CHANGELOG.md, shapely-poke/CHANGELOG.md, shapely-poke/Cargo.toml, shapely-samplelibc/Cargo.toml, shapely-spez/CHANGELOG.md, shapely-spez/Cargo.toml, shapely-trait/CHANGELOG.md, shapely-trait/Cargo.toml, shapely-types/CHANGELOG.md, shapely-types/Cargo.toml, shapely/CHANGELOG.md
* `shapely-opaque`: 3.1.0 -> 3.1.1
* `shapely-types`: 0.1.0
* `shapely-spez`: 3.1.0 -> 3.1.1
* `shapely-trait`: 3.1.0 -> 3.1.1
* `shapely-derive`: 3.1.0 -> 3.1.1
* `shapely`: 3.1.0 -> 3.1.1 (✓ API compatible changes)
* `shapely-codegen`: 3.1.0 -> 3.1.1
* `shapely-peek`: 3.1.0 -> 3.1.1 (✓ API compatible changes)
* `shapely-poke`: 3.1.0 -> 3.1.1
* `shapely-json`: 3.1.0 -> 3.1.1 (✓ API compatible changes)
<details><summary><i><b>Changelog</b></i></summary><p>
<blockquote>
- remove macos-only test
- shapedebug bye
- The great split
- more divides
</blockquote>
<blockquote>
- The great split
- more divides
</blockquote>
<blockquote>
- fix errors now
- Shapely is unsafe
- Fix tests etc.
- shapedebug bye
- getting there
- The great split
</blockquote>
<blockquote>
- fix errors now
- fix derive …
=> chore: release

README.md, facet/README.md, facet/templates/README.md.j2, templates/README.md.j2
I've found another typo in README.md, which I don't think is covered in #71.
=> fix: typo in README.md

README.md, facet-args/src/lib.rs, facet-codegen/src/tuples_impls.rs.j2, facet-core/src/_trait/impls/array_impl.rs, facet-core/src/_trait/impls/hashmap_impl.rs, facet-core/src/_trait/impls/slice_impl.rs, facet-core/src/_trait/impls/tuples_impls.rs, facet-core/src/_trait/impls/vec_impl.rs, facet-core/src/opaque/mod.rs, facet-json-read/src/deserialize.rs, facet-msgpack/src/from_msgpack.rs, facet-peek/src/lib.rs, facet-peek/src/map.rs, facet-peek/src/value.rs, facet-poke/src/enum_.rs, facet-poke/src/lib.rs, facet-poke/src/struct_.rs, facet-poke/src/value.rs, facet-poke/tests/poke_test.rs, facet-samplelibc/src/lib.rs, facet-toml/src/lib.rs, facet-urlencoded/src/lib.rs, facet-yaml/src/lib.rs, facet/README.md, facet/src/hacking/hacking.md, facet/templates/README.md.j2, templates/README.md.j2
This standardizes those types and their function names a little bit and removes the too-close-to-UB ones.
=> Re-jiggle OpaqueConst, Opaque, OpaqueUninit

facet-derive/src/lib.rs, facet-json-write/src/serialize.rs, facet-json-write/tests/json-write.rs
I understand that supporting references properly is still something to be figured out, but it seemed to me that supporting `'static` references (especially for string-like things) should be possible.
This is a "hammer it until it fits without really understanding the `shape`" implementation, so I wont take offense if I'm missing the mark completely, or if this just gets in the way of planned work.
I think on the surface level, it's reasonably safe to support even without proper ref support, as you still cannot `#[derive(Facet)]` on a type that has lifetime annotations (e.g. `struct Struct<'a>(&'a str)`).
=> Allow json serialization of static string types

facet-derive/src/lib.rs, facet-derive/src/process_struct.rs
Without this we may accidentally parse something successfully as a different thing due to syntax that we can't yet handle yet (like some specific type syntax for example).
While trying to change a parse rule incorrectly for example the macro resulted in parsing most of the record structs as unit structs without erroring!
=> Error on incomplete parse in facet-derive

Justfile, facet-core/Cargo.toml, facet-core/src/_trait/impls/hashmap_impl.rs, facet-core/src/_trait/impls/mod.rs, facet-core/src/_trait/impls/scalar_impls.rs, facet-core/src/_trait/impls/vec_impl.rs, facet-core/src/lib.rs, facet-core/src/types/mod.rs, facet-peek/Cargo.toml, facet-peek/src/enum_.rs, facet-peek/src/lib.rs, facet-poke/Cargo.toml, facet-poke/src/enum_.rs, facet-poke/src/lib.rs, facet-poke/src/struct_.rs, facet/Cargo.toml, facet/src/lib.rs
Quick summary
- `facet-core` only worked with `alloc` and not `core` because of `extern crate alloc`
- Some libraries were missing `no_std`
- Some std types were being used through the prelude
- `facet-poke` can support `alloc` without `std`
- I considered adding an `alloc` feature and a `#[cfg(not(feature = "alloc"))] compile_error!("")` but (1) that would be a breaking change and (2) unsure if that future proofing is worth it
- I considered doing this to other crates as well, like `facet-json` but (1) that would be a breaking change and (2) was unsure how far to go at this stage of facet
=> Fix `no_std` support

facet-derive/src/lib.rs, facet-derive/src/process_enum.rs, facet/tests/derive.rs
We don't introspect the types in the macro, so there is little reason to reconstruct parsers for them all, we just need to skip past them to parse the following relevant parts.
With this we should automatically support any type specifications in fields
=> Do not attempt to parse field types, that's not really our job

Justfile, facet-poke/Cargo.toml, facet-poke/src/lib.rs
This adds an `alloc` feature and fails if its not present, making it so when no-alloc support is added in the future, it isn't a breaking change.
This is a follow up to #123
BREAKING CHANGES: `cargo check -p facet-poke --no-default-features` now fails to build
=> feat(poke)!: Future proof for no-alloc support

facet-args/Cargo.toml, facet-derive/Cargo.toml, facet-json-read/Cargo.toml, facet-json-write/Cargo.toml, facet-msgpack/Cargo.toml, facet-peek/Cargo.toml, facet-poke/Cargo.toml, facet-pretty/Cargo.toml, facet-samplelibc/Cargo.toml, facet-toml/Cargo.toml, facet-trait/Cargo.toml, facet-urlencoded/Cargo.toml, facet-yaml/Cargo.toml, facet/Cargo.toml, sample/Cargo.lock
If there are path dependencies without versions, publishing doesn't work.
=> Specify crate versions

facet-core/src/types/mod.rs, facet-poke/src/struct_.rs, facet-poke/tests/struct.rs
The docs for `set` and `set_by_name` say that they should return an error if the field shapes don’t match.
However, they currently call `assert_type` and panic instead.
This PR adds a new `FieldError::TypeMismatch`, then returns it if there's a type mismatch.
(The alternative would be to change the docs, but returning an error seems friendlier)
=> Return error instead of panicking in `set`/`set_by_name`

facet-json/src/deserialize.rs, facet-json/src/parser.rs, facet-json/tests/json-read.rs, facet-reflect/src/poke/option.rs, facet-testhelpers/src/lib.rs
Added `PokeOption::build_in_place()` and `PokeOption::replace_with_some_opaque()` (not sure about the naming).
Also added support for parsing `null` in the JSON parser.
Closes #119
=> Opaque initialization of Some

facet-reflect/src/poke/struct_.rs
`unchecked_set` and `unchecked_set_by_name` don't actually check field shapes, so let's remove that from the docstring.
=> Fix `unchecked_set` docs about errors

facet-core/src/impls_alloc/smartptr.rs
`impls_alloc` is already gated by `feature = "alloc"` at the module level.
=> Remove unneeded cfg

Cargo.lock, facet-reflect/Cargo.toml, facet-reflect/src/lib.rs, facet-reflect/src/peek/enum_.rs, facet-reflect/src/peek/mod.rs, facet-reflect/src/wip/enum_.rs, facet-reflect/src/wip/flat_map.rs, facet-reflect/src/wip/mod.rs
I took the `Vec` route.  I carried over the `FlatMap` abstraction from clap but I made it a `Vec<(K, V)>`, rather than `(Vec<K>, Vec<V>)`, so I could get a trivial `retain`.  The latter is nicer for faster searching of keys (as cache lines aren't wasted) and can reduce binary size if you have `Vec<K>` or `Vec<V>` in other places.
Fixes #211
=> feat(reflect): Make wip available on alloc

Justfile, facet-json/Cargo.toml, facet-json/src/lib.rs, facet-json/tests/json-write.rs
`serialize` requires `std::io::Write`.  `deserialize` can get away without it because it only parses a `&str`.
Looking at `serde_json`
- `Serializer` requires `std` also to use `std::io::Write`
- `Deserializer` uses a custom `Read` trait that they have some custom specialization implemented for so they can work with slices and `std::io::Read`.  Maybe we can repurpose this technique to work for `serialize`.
=> feat(json): Allow `deserialize` with just `alloc`

facet-core/src/types/smartptr.rs, facet-reflect/tests/peek/smartptr.rs
This is a partial fix for #210: it allows people to manually implement `Facet` for "opaque" smart pointers, where we don't care about introspecting the shape of the pointed-to type.
(There will be a follow-up PR to add a `#[facet(opaque)]` syntax to the derive macro, but that one is messier)
I'm open to adjectives other than "opaque", which is used elsewhere in the codebase with a slightly different meaning.  Looking through a list of synonyms, the only one that I like is "veiled"; other suggestions are welcome.
=> Make `SmartPointerDef::pointee` optional

facet-core/src/impls_core/scalar.rs, facet-core/src/types/mod.rs, facet-core/src/types/scalar.rs
I have a small question about the scalar types in general:
are you only interested in things that "make sense" to a CPU of some sort? or do you include more ...indirect types that still count as scalar on a config file?
specifically, here are a bunch of types, in decreasing amounts of how likely they are to be useful for this project (independently of how hard they would be to describe the layout of)
- complex numbers (I think there are standard complex types in the cstdlib)
- decimal numbers
- datetime/timestamps 
- UUIDs
- fractions, algebraic number types (see https://chadnauseam.com/coding/random/calculator-app)
...also I just realised that the epsilon might not be necessary, since it is in theory computable as $2^{1-\text{MantissaDigits}}$ (MantissaDigits including any implicit …
=> [with discussion] scalars: add more types, and add info to numbers and floats

facet-core/src/impls_alloc/btreemap.rs
Without this `BTreeMap::<(), ()>::SHAPE` fails to compile.
=> Fix BTreeMap's SHAPE

facet-reflect/tests/wip/misc.rs
This was copy-pasted from an enum test but isn't correct here.
=> Fix incorrect comment

facet-json/src/deserialize.rs
I think there should be errors raised deliberately when we're able to parse (what we expect to be) a number but it's a string in the JSON
This should get the ball rolling by introducing a new type of `JsonErrorKind` for the situation when the number turns out to be a string
I tested it with [facet-validate](https://github.com/lmmx/facet-validate) like so
```rust
use facet::Facet;
use facet_validate::validate_json;
#[derive(Facet)]
struct FooBar {
foo: u64,
bar: String,
}
fn main() {
if result.is_empty() {
println!("No validation errors detected. The JSON validation didn't work!");
} else {
for error in &result {
println!("{}: {}", error.path, error.message);
}
}
}
```
gives
```
{"foo": 42, "bar": 42}
↑ StringAsNumber("42")
```
Suggestions for better enum names / any other feedback welcome …
=> feat(deserialize): handle number shaped StringAffinity

facet-core/src/ptr.rs
This function doesn't work as intended, and isn't used anywhere so let's get rid of it
fixes #241
=> remove PtrMut::write

facet-json/Cargo.toml, facet-json/src/deserialize.rs
- **build(feature-flag): new default feature "rich-diagnostics" to switch on `ariadne` Display for JsonParseErrorWithContext**
- requested in #258
- requested in #254 (review received after PR had merged)
- also from #254
=> build(ariadne): add "rich-diagnostics" default feature

facet-reflect/src/wip/mod.rs
To be used instead of this horrific incantation: https://github.com/facet-rs/facet/pull/259/files#diff-7c313d0af4bf7f525a9b8e4f98285f8c778fdbc88dc9de2c759c2efeaea29070R98-R101
=> chore(reflect): remove unnecessary `matches!` followed by the same `let`

facet-derive-emit/src/process_enum.rs
Fixes #271,
this was a regression I bisected to b0c2d91162093217a68fb8a6c86e6edfd6aa4bfd
We should probably add tests for `repr(C)` enums, since it seems there aren't any. I wanted to add but wasn't sure were to add them
=> Fix repr(C) enums

facet-json/src/deserialize.rs, facet-json/tests/integration/read.rs
- **fix(utf8): properly handle UTF-8 encoding in field names; add tests**
=> fix(utf8): deserialise UTF-8 encoded field names (closes #277)

facet-derive-emit/src/process_enum.rs, facet-derive-emit/tests/codegen.rs, facet-derive-emit/tests/snapshots/codegen__enum_with_discriminants.snap, facet-derive-parse/src/lib.rs
Fixes #284.
see the reference for how discriminants are assigned
https://doc.rust-lang.org/reference/items/enumerations.html#implicit-discriminants
BTW there is a lot of duplication between processing primitive enums and c-style enums. we should probably merge the code somewhat at some point
=> Allow manually defining enum discriminants

facet-json/src/deserialize.rs, facet-reflect/src/wip/mod.rs, facet-reflect/src/wip/put_f64.rs
Improve handling of number conversion to target Rust types using Wip::can_put_f64 and Wip::try_put_f64, reducing duplicated logic and delegating range checking to facet-reflect. Add put_f64 module to facet-reflect for this purpose.
=> Refactor JSON number deserialization to use Wip::try_put_f64

flake.lock, flake.nix, shell.nix
Introduced a development environment managed by [Nix](https://nixos.org). More info [here](https://nix.dev/#what-can-you-do-with-nix). It can be hooked up to direnv with [nix-direnv](https://github.com/nix-community/nix-direnv/) and the `use flake` command.
=> chore: add Nix flake

facet-dev/Cargo.toml, facet-dev/src/menu.rs
Termion does not support the platform, so this just stubs it out
=> Fix facet-dev compilation on windows

facet-json/src/deserialize.rs, facet-json/src/serialize.rs, facet-msgpack/src/to_msgpack.rs, facet-pretty/src/printer.rs, facet-reflect/src/peek/enum_.rs, facet-reflect/src/peek/list.rs, facet-reflect/src/peek/map.rs, facet-reflect/src/peek/option.rs, facet-reflect/src/peek/smartptr.rs, facet-reflect/src/peek/struct_.rs, facet-reflect/src/peek/value.rs, facet-reflect/src/wip/heap_value.rs, facet-reflect/src/wip/mod.rs, facet-reflect/tests/peek/facts.rs, facet-reflect/tests/wip/no_uninit.rs
This is going to be annoying to fix
The lifetimes as written are incorrect, easpecially `Wip::peek` returns `Peek` that is tied to our invariant lifetime, while it needs to be tied to the `Wip` as we could drop it before the `Peek` causing UB
=> Fix `Peek` lifetimes

facet-args/src/lib.rs, facet-core/src/types/mod.rs, facet-json/src/serialize.rs, facet-json/tests/integration/write/string.rs, facet-msgpack/src/from_msgpack.rs, facet-msgpack/src/to_msgpack.rs, facet-pretty/src/printer.rs, facet-reflect/src/wip/mod.rs, facet-toml/src/lib.rs, facet-urlencoded/src/lib.rs, facet-yaml/src/lib.rs
Follow up to #383, otherwise calling these with things containing lifetimes will tend to fail borrow check.
=> Make de/serialization API lifetimes more permissive 

facet-core/src/types/mod.rs, facet-json/src/deserialize.rs, facet-json/tests/integration/err.rs, facet-json/tests/integration/read/tuple.rs, facet-json/tests/integration/read/vec.rs, facet-reflect/src/wip/mod.rs
Working on finished tuple deserialisation
- Follow up to #314
Also contains ignored integration/error tests for empty tuple handling, treating it as an edge case we don't handle (yet)
- Tuple type includes unit type https://doc.rust-lang.org/reference/types/tuple.html
Snapshot test showing the error when the tuple is mis-sized could be made clearer (say "wrong size") but OK for now. Snapshot not included in this PR but can be seen if you un-ignore the 2 tests in `facet-json/tests/integration/err.rs`.
```
A: facet-json/tests/integration/snapshots/r#mod__integration__err__deserialize_tuple_wrong_size.snap
@@ -0,0 +1,11 @@
+---
+source: facet-json/tests/integration/err.rs
+expression: err
+---
+Error: Error at $
+   ╭─[ json:1:4 ]
+   │
+ 1 │ [10,20]
+   │    ┬  
+   │    ╰── Field error for …
```
=> feat: tuple deserialisation

facet-core/src/impls_alloc/arc.rs, facet-core/src/impls_alloc/btreemap.rs, facet-core/src/impls_alloc/rc.rs, facet-core/src/impls_alloc/vec.rs, facet-core/src/impls_core/array.rs, facet-core/src/impls_core/option.rs, facet-core/src/impls_core/scalar.rs, facet-core/src/impls_core/slice.rs, facet-core/src/impls_core/smartptr.rs, facet-core/src/impls_std/hashmap.rs, facet-core/src/impls_std/path.rs, facet-core/src/opaque.rs, facet-core/src/types/mod.rs
We should always use `Self` here or we run into risks of forgetting a defaulted type parameter (as happened in the hashmap impl for example).
This also deduplicates some code with a helper.
=> Fix some incorrect `Layout`/`ConstTypeId` `Shape` building

facet-core/src/impls_alloc/btreemap.rs, facet-core/src/impls_alloc/vec.rs, facet-core/src/impls_core/array.rs, facet-core/src/impls_core/fn_ptr.rs, facet-core/src/impls_core/slice.rs, facet-core/src/impls_core/tuple.rs, facet-core/src/impls_std/hashmap.rs, facet-core/src/macros.rs, facet-core/src/types/value.rs, facet-dev/src/main.rs, facet/src/sample_generated_code.rs
Opposed to manually filling it out. A bunch of our impls are lacking this where drop glue is involved, an example being arrays. While they don't implement `Drop`, they may contain types that are `Drop` and such can potentially have a destructor.
=> Automatically populate `drop_in_place` when vtable building

DEVELOP.md
https://github.com/facet-rs/facet/issues/408 removed using the `Cargo.toml` metadata to highlight contributors but `DEVELOP.md` still referenced old process
Remove incorrect documentation, I couldn't find a existing issue about what will replace this so opted for full removal instead of replacing with `# TODO` / issue link.
=> fix(docs) Remove reference to old process

CLAUDE.md, facet-derive-emit/src/lib.rs, facet-derive-emit/src/process_enum.rs, facet-derive-emit/src/process_struct.rs, facet-derive-emit/tests/codegen/snapshots/r#mod__codegen__enum_with_multiple_attributes_per_variant.snap, facet-derive-emit/tests/codegen/snapshots/r#mod__codegen__enum_with_renamed_variants_and_fields.snap, facet-derive-emit/tests/codegen/snapshots/r#mod__codegen__mixed_rename_and_sensitive_attributes.snap, facet-derive-emit/tests/codegen/snapshots/r#mod__codegen__struct_with_facet_attributes.snap, facet-derive-emit/tests/codegen/snapshots/r#mod__codegen__struct_with_renamed_field.snap, facet-derive-emit/tests/codegen/snapshots/r#mod__codegen__tuple_struct_with_renamed_field.snap, facet-json/tests/integration/read/rename.rs, tests/derive/raw_identifiers.rs
Note that there is no way to go back to the original field name.
Closes #402
=> Support raw identifiers in field names

facet-args/src/lib.rs, facet-args/tests/simple.rs
Using common casing for multi-word arguments results in error. As the mismatch in common kebab-case used for arguments does not find the snake_case Facet field.
Normalize the keys for non-short named arguments to snake case. This initial work makes 2 assumptions:
- GNU/Unix kebab-casing is the initial norm
- Facet derived struct will be built with snake_cased field names
I will hopefully tackle making these less implicit assumption by aligning with the json crate on how it is tackling this casing aspect
Note: This is stacked on: https://github.com/facet-rs/facet/pull/459 both PRs are so small that I don't think this complicates review.
=> feat(args) - Handle multi word args

Cargo.lock, facet-args/Cargo.toml, facet-args/README.md, facet-args/README.md.in, facet-args/src/error.rs, facet-args/src/lib.rs, facet-args/tests/simple.rs
- Expand error handling, replace panic! / unwraps with ArgsError, switch to expect where applicable
- Add some test coverage
- Add ignored testcase for some currently broken functionality 
Meta-question: @fasterthanlime would you prefer if I create issues for the TODOs and ASSUMPTIONs re: functionality gaps that I am including in the code? I am hoping to tackle them soon but I could also just vanish into the ether and have left some potential confusing code artifacts 😁
=> feat(facet-args): Expand error handling

facet-args/src/lib.rs, facet-args/tests/simple.rs
When a command line argument is unset we should fallback to unset defaults for `bool` and `Option<_>` (not in this PR). Currently this results in a reflect error due to uninitialized fields. Which is surprising behaviour in the case of command line arg parsing, where not setting things is explicitly required in some cases for the desired behaviour.
Find any unset bool fields and set them to `"false"`
This feels like a naff solution. The friction I am seeing is the within the core crates, the facet attributes are normally explicitly set-up upfront on the struct i.e `default` etc. which makes sense for a parsers like `json` etc. where you want to be very explicit about the behaviour when something you expect to be present, isn't. In the case of command line arguments there is more implicit …
=> fix(args) - unspecified bool arguments should be assumed false 

Cargo.lock, facet-core/src/impls_camino.rs, facet-pretty/Cargo.toml, facet-pretty/tests/camino.rs
Hi,
First of all, thanks again for your work on Facet!
So this is my first attempt at a contribution: make facet-pretty display Utf8PathBuf and Utf8Path values using their implementation of the Display trait.
Please bear in mind that I have no idea what I'm doing, and basing those types' vtables on String and `&str` may very well have broken something or killed the performance of something else that I have no idea about :) So feel free to point out anything that might go wrong or be pessimized as a result of those changes; it's fine if you don't accept them at all.
Thanks again, and keep up the great work!
G'luck,
Peter
=> pretty: support camino

facet-derive-emit/src/process_enum.rs, facet-derive-emit/tests/codegen/mod.rs, facet-derive-emit/tests/codegen/snapshots/r#mod__codegen__repr_c_enum_empty_struct_variant.snap, facet-derive-emit/tests/codegen/snapshots/r#mod__codegen__repr_c_enum_lifetime_field.snap
Small fix for #447 (facet-derive-emit), proc macro generation for enums with empty struct variants or lifetime fields + test coverage
```rust
// Handle empty fields case explicitly
let struct_fields = if fields_with_types.is_empty() {
// Only add phantom data for empty struct variants
quote! { _phantom: #phantom_data }
} else {
// Add fields plus phantom data for non-empty struct variants
quote! { #(#fields_with_types),*, _phantom: #phantom_data }
};
```
=> fix derive macro edge cases

facet-serialize/src/lib.rs, facet-toml/src/serialize.rs
Many formats don't need to implement everything for all number types, and they can handle beginning and ending of objects differently.
=> refactor(serialize): make many trait methods optional

Cargo.lock, facet-dev/Cargo.toml, facet-jsonschema/Cargo.toml, facet-kdl/Cargo.toml, facet-toml/Cargo.toml
Maybe we can somehow embed cargo-machete in the pipeline? It's a very useful tool.
=> chore(deps): cleanup unused dependecies with cargo-machete

Cargo.lock, facet-toml/Cargo.toml, facet-toml/benches/compare_serde.rs
The nested benchmark doesn't work because the toml crate itself can't handle it.
Results running on my PC:
```
Running benches/compare_serde.rs (target/release/deps/compare_serde-2dac0ce75db18f24)
Timer precision: 20 ns
compare_serde                fastest       │ slowest       │ median        │ mean          │ samples │ iters
├─ Wide - facet_deserialize  67.88 µs      │ 150.6 µs      │ 89.17 µs      │ 88.16 µs      │ 100     │ 100
├─ Wide - facet_serialize    33.48 µs      │ 85.46 µs      │ 34.12 µs      │ 35 µs         │ 100     │ 100
├─ Wide - serde_deserialize  33.78 µs      │ 86.08 µs      │ 34.07 µs      │ 35.03 µs      │ 100     │ 100
╰─ Wide - serde_serialize    23.79 µs      │ 36.13 µs      │ 24.18 µs      │ 24.74 µs      │ 100     │ 100
```
=> test(toml): add wide benchmark

facet-core/src/impls_core/array.rs, facet-reflect/src/peek/list_like.rs, facet-reflect/src/peek/mod.rs, facet-reflect/src/peek/value.rs, facet-reflect/tests/peek/list_like.rs, facet-reflect/tests/peek/mod.rs, facet-serialize/src/lib.rs
Lists, arrays and slices are very similar, so this abstracts over `Peek`s of them.
I wasn't sure if I should just modify `facet_reflect/src/peek/list.rs`
since lists may have additional behaviour in the future different from
slices and arrays.
This additionally fixes `get_item_ptr` vtable entry for arrays, since it didn't use
`index` (and just returned the pointer to the original array).
=> Add `PeekListLike` abstraction and fix serialize and `get_item_ptr` for arrays

facet-deserialize/src/lib.rs, facet-json/src/deserialize.rs
I think it will be quite hard to implement most deserializers without any state between the passes.
=> refactor(deserialize)!: make deserialize format stateful

facet-core/src/impls_core/mod.rs, facet-core/src/impls_core/ops.rs
I haven't used Facet much so please review this carefully, I'm likely to have missed something. I'd like to use Facet to build a debugger for the parser I'm building and it's using `core::ops::Range<usize>` so I'd like `Range` to implement `Facet` so that I can derive `Facet` for my struct that's containing the range.
My parser is also using  `core::iter::Peekable` so I'd also like to implement Facet for it but I'm not sure what do about its private fields? Omit them?
=> feat: support core::ops::Range

Cargo.lock, Cargo.toml, facet-args/src/lib.rs, facet-args/tests/simple.rs, facet-core/src/impls_core/pointer.rs, facet-core/tests/pointer.rs, facet-reflect/tests/peek/facts.rs, facet-reflect/tests/wip/misc.rs
Some fallout from #462 — reference types showed up as raw pointer types, the type_name was slightly incorrect, etc. Just following up on these since it's impacting facet-args, for example.
=> fix: References are not pointers, also, resuscitate facet-args

CLAUDE.md, facet-json/src/deserialize/tokenizer.rs, facet-json/tests/issue_530_test.rs
Fixed issue #530 by properly implementing Unicode \uXXXX escape sequence parsing in the JSON tokenizer. Added tests for various Unicode escape scenarios to ensure proper handling.
- Parses 4-digit hex code into a Unicode code point
- Properly converts to UTF-8 and adds to output buffer
- Maintains compatibility with other escape sequences
- Added comprehensive test suite for Unicode escapes
=> fix: Add support for Unicode escape sequences in JSON strings

facet-pretty/src/printer.rs, facet-pretty/tests/pretty_print.rs
Before e.g. (1,2) was printed as:
unsupported peek variant: (1, 2)
where the printed `(1,2)` was just the core::fmt::Debug formatting. This commit adapts the printer to reuse the list printing logic so that e.g. (1,2) becomes:
(i32, i32) (
1,
2,
)
=> fix(pretty): support tuples

facet-core/src/impls_alloc/boxed.rs, facet-core/src/impls_alloc/mod.rs
Pretty self-explanatory: this PR adds a new impl of `Facet` for `Box<T>`
There was already a [`KnownSmartPointer::Box`](https://docs.rs/facet/0.25.1/facet/enum.KnownSmartPointer.html#variant.Box) variant, so this change ended up being pretty minimal. Full disclosure: I'm still not fully up to speed on all the inner workings of facet and I started from the `Arc<_>` impl as a basis, so I'm _hoping_ everything here holds up to scrutiny. Miri isn't complaining so I take that as a good sign
---
facet's been on my radar for a while, and I finally have a use-case where I _think_ it'll help solve a problem that I can't solve (easily) with Serde today. While working through the changes, I was surprised to see that `Box<_>` didn't have a `Facet` impl... I saw this as a good chance to get my hands a …
=> Add `Facet` impl for `Box`

Cargo.lock, facet-core/Cargo.toml, facet-core/src/impls_time.rs, facet-core/src/lib.rs, facet-json/Cargo.toml, facet-json/tests/integration/read.rs, facet-json/tests/integration/read/datetime.rs, facet-json/tests/integration/write.rs, facet-json/tests/integration/write/datetime.rs, facet-reflect/Cargo.toml, facet-serialize/src/lib.rs
While doing this it reminded me that I think `ScalarType` is kinda duplicated with ScalarAffinity.
And also that I think DateTime affinities should have vtables.
=> Add support for the time crate

facet-core/src/impls_alloc/btreeset.rs, facet-core/src/impls_alloc/mod.rs, facet-core/src/impls_std/hashset.rs, facet-core/src/impls_std/mod.rs, facet-core/src/types/def/list.rs, facet-core/src/types/def/mod.rs, facet-core/src/types/def/set.rs
Closes #247
This PR adds initial support for sets with a new `Def::Set(SetDef)` variant-- plus a new `SetVTable` to go along with it. It also adds impls of `Facet` for both `HashSet<T, S>` and `BTreeSet<T>`
`SetVTable` has the following methods:
- `init_in_place_with_capacity(PtrUninit, usize) -> PtrMut`
- `insert(PtrMut, T) -> bool`
- `len(PtrConst) -> usize`
- `contains(PtrConst, T) -> bool`
- `iter(PtrConst) -> PtrMut`
From a high level, I was split between adding set as its own def, or if I should try to build on map (or possibly list). Personally, I feel it's right in between map and a list, but different enough from either to warrant its own category. I learned about JSON Structure after spotting #471, and was ultimately swayed because [a set is one of the core types in JSON …
=> Add new `SetDef` and impls for `HashSet` and `BTreeSet`

Cargo.lock, facet-args/Cargo.toml, facet-args/src/defaults.rs, facet-args/src/error.rs, facet-args/src/lib.rs, facet-args/src/parse.rs, facet-args/tests/defaults.rs, facet-args/tests/parse.rs, facet-args/tests/simple.rs, facet-deserialize/src/lib.rs
- Refactor of facet-args to rely on facet-deserialize, with structured default field parsing (i.e. done on a StackRunner)
- which was then extracted into a dedicated module `defaults.rs` (with tests)
- default handling done in dedicated functions moved over to a proper module `parse.rs` (with tests)
- I am still not using a Format trait (I drafted it but it didn't take and I walked it back), but it _is_ using facet-deserialize where it wasn't before so I'd suggest going with this?
- Note: 2 small `pub` changes in facet-deserialize (`original_input` field and `pop` fn)
- :shipit: Squished into one commit, ship/review at will
- **stretch goal** - while this PR is ready, I wanted to try developing a format trait and sort of got it, but it's a bit involved and still unsure if it will take so …
=> refactor(facet-args): rely on facet-deserialize

Cargo.lock, facet-core/Cargo.toml, facet-core/src/impls_jiff.rs, facet-core/src/lib.rs, facet-json/Cargo.toml, facet-json/tests/integration/read/datetime.rs, facet-json/tests/integration/write/datetime.rs, facet-reflect/Cargo.toml
There are also a lot more types in `jiff`, I picked the ones that represent date-time, should we also add implementations for the other types?
=> feat(core): add `jiff` implementations

facet-derive/src/lib.rs, facet/src/lib.rs
Still needs a lot more documentation, but at least it's a start.
=> docs(derive): describe the global attributes on the derive macro

facet-core/src/impls_alloc/btreemap.rs, facet-core/src/impls_alloc/btreeset.rs, facet-core/src/impls_std/hashmap.rs, facet-core/src/impls_std/hashset.rs, facet-core/src/types/def/iter.rs, facet-core/src/types/def/map.rs, facet-core/src/types/def/mod.rs, facet-core/src/types/def/set.rs, facet-reflect/src/peek/map.rs
Relates to #578
This PR adds a new `IterVTable`, which covers the functionality of both the prior `MapVTable` and `SetVTable`. The new vtable also has an `init_with_value` function, which also replaces both previous `iter` functions (this was so the iter vtable could have both the `init` and `dealloc` functions for symmetry)
To account for maps returning key/value pairs and sets returning just values, `IterVTable` includes both `next`/`next_back` functions (required, yields a single value) plus `next_pair`/`next_pair_back` functions (optional, yields two values). This feels a little gross, but my thought was that you can view a map like an iterator over its values, so it kinda makes sense?[^iter-keys] (I also have an alternative idea for implementing this but it's also a little gross, so …
=> Refactor `MapVTable` and `SetVTable` to share a common `IterVTable`

facet-args/src/defaults.rs, facet-deserialize/src/debug.rs, facet-deserialize/src/error.rs, facet-deserialize/src/lib.rs, facet-deserialize/tests/input_types.rs, facet-json/src/iterative/deserialize.rs
- **feat(deserialize): support multiple input types via generic `Format`**
**Summary**: refactor with no change to behaviour, allows us to support `&str` arguments in a Format needed for facet-args
**Motivation**: JSON is a sequence of bytes, but the OS splits up the CLI args for us when making `std::env::args` so we need a way to iterate over those strings, this allows us to do that
This PR keeps the currently hardcoded `Format` input type as `u8` as the default while adding the ability to take `&str`
It demonstrates usage of this in the 2 tests included, both deserializing the same Facet struct with one field `nom: String` (note the change in string type in this PR refers to the deserialisation data _input_ type not the Facet field type)
- `u8` test (which we already know works thanks …
=> feat(deserialize): multi-input type support via generic `Format`

facet-core/src/impls_alloc/btreemap.rs, facet-core/src/impls_std/hashmap.rs, facet-core/src/types/def/iter.rs, facet-core/src/types/def/map.rs, facet-core/src/types/def/set.rs, facet-reflect/src/peek/map.rs
Follow-up to #617
This PR builds on #617, with a different way to handle the "map vs. set" iteration problem. The original way was to basically offer two different ways to iterate: `next` which returnes a single `PtrConst`, and `next_pair` which returns a pair of `PtrConst` values (i.e. the key and value of a map)
This PR tweaks the new `IterVTable` type to be generic over what `next` should return-- the iteratee. Sounds easy enough... except `NextFn` (like all vtable methods) uses [Higher-Ranked Trait Bounds](https://doc.rust-lang.org/nomicon/hrtb.html) so it can be generic over lifetimes. To properly type this, we need to "apply" this higher-ranked lifetime to the generic type.
The tool we need for that is a Higher-Kinded Type. Luckily, …
=> Make `IterVTable` generic over the iteratee

facet-core/src/impls_alloc/vec.rs, facet-core/src/types/def/list.rs, facet-reflect/src/peek/list.rs, facet-reflect/src/peek/list_like.rs
Closes #578, should unblock #597 (I think)
This PR updates `ListVTable` with the following changes:
- Make `as_ptr` / `as_mut_ptr` fields optional
- Add new `get` / `get_mut` fields to get an element by index in the list
- Add new `iter_vtable` field: a vtable for creating/using/destroying an iterator for the list
- See these PRs for more context: #617, #618
- The iterators aren't all that useful when the `get` method is O(1), but that also means that more unusual collections can fit into `ListDef` more naturally (e.g. `LinkedList`, which can't efficiently implement `get` but can still iterate efficiently... relatively speaking)
I also updated `PeekList` and `PeekListLike` to account for lists that have / don't have `as_ptr`. Basically, it tries to use `as_ptr` as a fast path if …
=> Update list vtables to allow for more types of lists

docs/templates/main-style.css.jinja
I noticed that the `<nav>`, on the right of the screen, was overflowed and the text was running vertically past the end of it's container. Letting the y axis scroll fixed this :)
wasn't sure how to organize the CSS, but after the height seemed like a smart place.
=> Allow nav to scroll on facet.rs website

facet-args/tests/sequence.rs
I began implementing `Vec` support for facet-args but then found something else would need to come first, so am putting these tests in for now, set as `#[ignore]`, while I drop the other approach I was taking [which won't work without preparatory work beforehand]
=> test(args): TDD for `Vec` support

facet-reflect/src/peek/enum_.rs, facet-reflect/src/peek/fields.rs, facet-reflect/src/peek/mod.rs, facet-reflect/src/peek/struct_.rs, facet-reflect/src/peek/tuple.rs, facet-serialize/src/lib.rs
This PR makes it so `facet-serialize` no longer requires [`DoubleEndedIterator`](https://doc.rust-lang.org/stable/std/iter/trait.DoubleEndedIterator.html) when iterating over values. In turn, this also means that serialization can use plain iterator values in more places, without resorting to collecting e.g. into a `Vec`.
The "trick" is in `SerialzeTask`, which now holds iterators wherever possible. When popped from the stack, it gets the next value from the iterator then pushes it back onto the stack (until the iterator is empty).
I was hoping this would lead to perf improvements, but locally, I wasn't seeing a noticeable difference... I still felt like this change had other minor benefits (e.g. less memory use during iteration, `iter_vtable` for `HashMap` no longer needs to collect its …
=> Refactor serialization to avoid reversing or collecting iterators

facet/Cargo.toml
I noticed that the root `facet` crate didn't have features for `ulid` or `url`
=> Add missing `ulid` and `url` features to root crate

facet-args/src/arg.rs, facet-args/src/fields.rs, facet-args/src/format.rs, facet-args/src/lib.rs, facet-args/src/parse.rs, facet-args/src/results.rs
- **refactor(args):**
- extract parse module for simpler format
- enum of ArgType
- short flag lookup
- various field helpers
- result wrappers (avoid `map`/`map_err` boilerplate bloat)
**Summary** Uses combinators in facet-args rather than early returns, tuck `DeserErrorKind` creation away in field helpers so span handling becomes relatively more visible
- The `DeserErrorKind` can be abstracted away, it's just bloating the main business logic (and making it very indented and hard to read!), the important thing is to keep the span handling inline (as this will be central to control when doing subspan logic, and to abstract it away would make that require arg passing which'd lose visibility)
- For instance using a helper to do the short field name lookup allows us to keep visibility of the …
=> refactor(args): `ArgType` enum, various field helpers

facet-args/src/fields.rs, facet-args/src/format.rs, facet-args/src/results.rs
- **refactor(args): standardise spans in runner and errors**
**Summary**: Raw error spans don't actually use the raw span length when converting to byte-index over the input (`to_cooked` method), i.e. an error is always for a single arg. This means we can use 0-length spans (used by the stack runner to mean "do not advance to the next arg") and 1-length spans (to mean "step forward") for our errors too, without modification, except for the one odd case where we subtract 1 from the arg index.
- This lets us discard error span length handling entirely.
- This further simplifies the facet-args central `next` routine to the point it's now less than 100 lines, and easy to read.
=> refactor args standardise erorr spans

facet-core/src/impls_core/pointer.rs, facet-core/src/types/value.rs, facet-reflect/tests/peek/facts.rs
I don't know why the last test in `test_mut_ref` doesn't work when checking its `PartialEq` and `Ord` implementations. Seems like a bug in `Facet` somewhere...
=> Fix marker traits for references and also test marker traits in facts

Cargo.lock, facet-core/Cargo.toml, facet-core/src/impls_bytes.rs, facet-core/src/lib.rs, facet-core/src/types/def/list.rs, facet-deserialize/src/lib.rs, facet-json/Cargo.toml, facet-json/tests/bytes.rs, facet-json/tests/option.rs, facet-reflect/src/wip/mod.rs, facet-reflect/src/wip/pop.rs, facet/Cargo.toml
Closes #597
This PR adds `bytes` as an optional dependency / feature-- when enabled, it impls `Facet` for the [`Bytes`](https://docs.rs/bytes/latest/bytes/struct.Bytes.html) and [`BytesMut`](https://docs.rs/bytes/latest/bytes/struct.BytesMut.html) types.
Turns out [I was wrong before](https://github.com/facet-rs/facet/issues/578#issue-3055805317): both `Bytes` and `BytesMut` are backed by a single contiguous slice. That means they both provide an `as_ptr` function for faster iteration
Dealing with `Bytes` still ended up being a little tricky because it's immutable. I felt the most direct option for now was to make mutating functions from `ListVTable` optional, making it effectively immutable. That means you can't e.g. deserialize `Bytes` (unless it's empty), since `Wip` can't insert any …
=> Add support for the `bytes` crate

facet-core/src/impls_alloc/vec.rs, facet-core/src/impls_core/fn_ptr.rs, facet-core/src/impls_core/pointer.rs, facet-core/src/impls_core/tuple.rs, facet-core/src/impls_std/hashmap.rs, facet-core/src/macros.rs, facet-core/src/types/value.rs, facet-reflect/tests/peek/facts.rs, facet/src/sample_generated_code.rs, facet/tests/value_vtable_facts.rs
I don't know if `Sized` should be added to `MarkerTraits`. It is definitely a marker trait, however we already store whether a type is `Sized` elsewhere.
=> Add UnwindSafe and RefUnwindSafe to marker traits

facet-toml/src/serialize/mod.rs
Change the signature of `TomlSerializer::push_key` to take an `impl Into<Cow<'shape, str>>`, and update call-sites accordingly.
=> facet-toml: ser: TomlSerializer: push_key can coerce an argument

facet-json/src/serialize.rs, facet-json/tests/bytes.rs, facet-reflect/src/peek/value.rs, facet-serialize/src/lib.rs
Previously, &[u8] references were serialized as null in JSON. This adds proper support for serializing them as arrays of numbers, matching the behavior of Vec<u8> and other byte containers.
- Add as_bytes() method to Peek for detecting &[u8] references
- Update serializer to check for byte slices and use serialize_bytes()
- Add comprehensive tests for various byte slice scenarios
=> Fix JSON serialization of &[u8] slices

facet-json/src/lib.rs, facet-json/tests/escapes.rs
- Fixed critical bug in write_json_escaped_char where raw bytes were used instead of extracting hex digits (nibbles) from Unicode code points
- The bug caused panic when serializing control characters like \u{7F} because char::from_digit(127, 16) returns None (127 > 15)
- Now correctly extracts 4-bit nibbles using bit shifts and masking
- Added comprehensive test suite covering:
* All ASCII control characters (0x00-0x1F, 0x7F)
* Special escape sequences remain unaffected (\n, \r, \t, etc.)
* Mixed strings with control characters
* Roundtrip serialization/deserialization
* Hex digit generation edge cases
- All existing facet-json tests continue to pass
=> Fix ASCII control character hex escaping bug and add comprehensive tests

facet-macros-emit/src/function/emit.rs, facet-macros-emit/tests/codegen/function.rs, facet-macros-emit/tests/codegen/snapshots/r#mod__codegen__function__function_with_complex_doc_comments.snap, facet-macros-emit/tests/codegen/snapshots/r#mod__codegen__function__function_with_doc_comments_and_quotes.snap, facet-macros-emit/tests/codegen/snapshots/r#mod__codegen__function__function_with_mixed_attributes.snap, facet-macros-emit/tests/codegen/snapshots/r#mod__codegen__function__function_with_multiple_doc_comments.snap, facet-macros-emit/tests/codegen/snapshots/r#mod__codegen__function__function_with_mutable_references.snap, facet-macros-emit/tests/codegen/snapshots/r#mod__codegen__function__function_with_no_parameters.snap, facet-macros-emit/tests/codegen/snapshots/r#mod__codegen__function__function_with_no_return_type.snap, facet-macros-emit/tests/codegen/snapshots/r#mod__codegen__function__function_with_single_doc_comment.snap, facet-macros-emit/tests/codegen/snapshots/r#mod__codegen__function__function_with_string_parameter.snap, facet-macros-emit/tests/codegen/snapshots/r#mod__codegen__function__generic_function_multiple_params.snap, facet-macros-emit/tests/codegen/snapshots/r#mod__codegen__function__generic_function_simple.snap, facet-macros-emit/tests/codegen/snapshots/r#mod__codegen__function__generic_function_with_docs.snap, facet-macros-emit/tests/codegen/snapshots/r#mod__codegen__function__simple_function.snap, facet-macros-parse/src/function/func_sig.rs, facet/tests/functions.rs
- **feat(fn): capture function docstring in shape**
I added some debug logging initially, which showed what is going through here:
```
Finished `test` profile [unoptimized + debuginfo] target(s) in 0.03s
────────────
Nextest run ID caab8be2-8433-41c7-b96d-ab162522fcc2 with nextest profile: default
Starting 4 tests across 1 binary (33 tests skipped)
PASS [   0.002s] facet-macros-parse function::func_sig::tests::test_function_without_doc_comments
──── STDOUT:             facet-macros-parse function::func_sig::tests::test_function_without_doc_comments
running 1 test
DEBUG: parse_function_signature called with input: fn no_docs (x : i32) -> i32 { x * 2 }
DEBUG: Successfully parsed FnSignature
DEBUG: Found 0 attributes
DEBUG: Final documentation: None
test …
```
=> feat(fn): capture function docstring in shape

facet-toml/src/serialize/mod.rs
This introduces a wrapper type `KeyStack` in order to provide a `Display` implementation, avoiding allocating multiple `String`s while tracing.
This falls into the territory of a micro-optimization.
=> facet-toml: ser: init newtype KeyStack with Display impl

docs/content/_index.md, facet-core/src/types/mod.rs, facet-kdl/src/lib.rs, facet-macros-emit/src/parsed.rs, facet-msgpack/src/deserialize.rs, facet-reflect/README.md, facet-reflect/README.md.in, facet-reflect/src/partial/mod.rs, facet-toml/src/deserialize/error.rs, facet-urlencoded/src/lib.rs, facet/src/lib.rs
I noticed that the `Wip` link on https://facet.rs/ was broken (since it was renamed to `Partial`); this PR fixes that and other obvious cases.
=> Rename `Wip` → `Partial` in docs and comments

facet-args/src/format.rs, facet-args/src/lib.rs
This PR just adds a function to make the ergonomics of parsing command line arguments provided directly from std::env::args a bit nicer.
=> Add a new QOL function to parse std args.

facet-dev/src/main.rs
I was being gaslit by `facet-dev`'s invocation of `nextest`, it was telling me that snapshots were changing at points in the history that made no sense. After chasing my tail for a while, I noticed it was because it skips any more jobs after a failure, but allows the current jobs to finish. I took its suggestion of using the `--no-fail-fast` flag. I still have no idea how `facet-dev` works, or why `nextest` changes the snapshots insead of `codegen`, why this is separate from `cargo insta test`, and so many other questions.
=> facet-dev: prepush: nextest: do not fail fast

facet-core/src/types/mod.rs
Something that I'm not sure about is: there are some fields which are optionally shown, but `Some(...)` does not appear in the output to indicate that they are indeed `Option`. For the time-being, I have decided it's okay to be XXX, because if the developer needs the field they will quickly notice the `Option`-ality from the LSP's feedback or the compiler yelling at them. Still, I'm not a fan of lying in the `Debug` formatting.
There are more comments in the code and descriptions on certain commits, but here's an overview:
- `type_identifier` - First, because it tells you what type the `Shape` is for.
- This position orients the reader immediately.
- `type_params` - Second, because it forms a complete path to the monomorphized type.
- Distinguishes between `Shape`s with the same …
=> facet-core: rework impl Debug for Shape

Cargo.lock, Cargo.toml, facet-inspect/Cargo.toml, facet-inspect/README.md, facet-inspect/README.md.in, facet-inspect/src/diff.rs, facet-inspect/src/inspect.rs, facet-inspect/src/lib.rs
Hi !
This is an experimentation on allowing facet objects to be diffed.
I make this PR early to gather feedback and make sure that I go the right way.
The key elements of this PR are:
- Introducing Paths allowing to navigate a facet object
- Creating an iterator that will traverse a given facet object and yield a (path, peek) tuple
- using this iterator to create a diff between two facet objects
I have two things in mind with this addition, allowing facet_assert (https://github.com/facet-rs/facet/issues/339) and allowing sending diffs over the network and apply them like patches to existing objects.
=> Allowing to inspect facet objects (get field by path + object diff)

facet-toml/src/deserialize/mod.rs, facet-toml/tests/deserialize/struct_.rs
Noticed the toml deserializer wasn't respecting `#[facet(default = ...)]`.
This fixes it by re-ordering the if-else chain to check for `default` before checking if the type is `Option<T>` and also calling `set_field_default` instead of `set_default` when `field.vtable.default_fn` is present.
=> Fix `#[facet(default = ...)]` in facet-toml

Cargo.toml, facet-bench/Cargo.toml, facet-bench/benches/reflect.rs, facet-core/src/typeid.rs, facet-core/src/types/characteristic.rs, facet-core/src/types/mod.rs, facet-core/src/types/ty/enum_.rs, facet-core/src/types/ty/pointer.rs, facet-core/src/types/ty/user.rs, facet-core/src/types/value.rs, facet-reflect/src/partial/iset.rs, facet-reflect/src/partial/mod.rs, facet-reflect/src/peek/enum_.rs, facet-reflect/src/peek/fields.rs, facet-reflect/src/peek/list.rs, facet-reflect/src/peek/list_like.rs, facet-reflect/src/peek/map.rs, facet-reflect/src/peek/option.rs, facet-reflect/src/peek/set.rs, facet-reflect/src/peek/smartptr.rs, facet-reflect/src/peek/tuple.rs, facet-reflect/src/peek/value.rs, facet-reflect/src/scalar.rs
Here's my results of tinkering with reflection benchmarks and profilers.
The challenge is hard because it's difficult to know what actually matters, especially for a broad API with many potential use cases. It's super hard to get really conclusive, but these changes are quite conservative and should fall in the "well at least it can't hurt" category.
I've attacked the problem from a couple of angles:
1. Profiling existing benchmarks, especially `json`.
2. Profiling a new microbenchmark, `reflect`.
3. Manually looking at the disassembly for a couple of probably-hot functions to make educated guesses about performance impact.
I've been using Visual Studio and AMD uProf to measure and analyze the results.
**Key takeaway:** Facet is pretty fast, and there's not a huge amount of low-hanging …
=> Reflection perf tinkering

facet-json/src/serialize.rs, facet-json/tests/hashmap.rs
This is the follow up for https://github.com/facet-rs/facet/pull/819
A helper method is introduced to serialize all numbers that can serve as a key in an object / `HashMap` (i.e. floats are excluded because they can't be used as keys).
This also removes a bit of redundancy in the number serialization code, which is nice.
=> Generate string keys for all numbers

Cargo.lock, Cargo.toml, facet-asn1/CHANGELOG.md, facet-asn1/Cargo.toml, facet-asn1/README.md, facet-asn1/README.md.in, facet-asn1/src/lib.rs, facet-asn1/src/tag.rs, facet-asn1/tests/mod.rs
Draft PR as there are a handful more types I'd like to support out-of-the-box as well as some test coverage improvements. PR reviews are welcome nonetheless.
=> Add facet-asn1 with initial DER support

facet-serialize/CHANGELOG.md, facet-serialize/src/lib.rs, facet-xdr/CHANGELOG.md, facet-xdr/src/lib.rs, facet-xdr/tests/mod.rs
=> Fix serialization for Option<T> in XDR
