facet-rs/facet

- Cargo.lock
- Cargo.toml
- shapely-core/src/lib.rs
- shapely-core/src/scalar_contents.rs
- shapely-core/src/scalar_contents_tests.rs
- shapely-core/src/scalar_impls.rs
- shapely-core/src/shape.rs
- shapely-pretty/Cargo.toml
- shapely-pretty/README.md
- shapely-pretty/examples/basic_usage.rs
- shapely-pretty/src/ansi.rs
- shapely-pretty/src/color.rs
- shapely-pretty/src/display.rs
- shapely-pretty/src/lib.rs
- shapely-pretty/src/printer.rs
- shapely-pretty/tests/pretty_print.rs
- shapely/README.md
It allows pretty-printing any shapely value.
> Introduce shapely-pretty

- shapely-core/src/hashmap_impl.rs
- shapely-core/src/partial.rs
- shapely-core/src/shape.rs
- shapely-core/src/shape/pretty_print.rs
- shapely-core/src/slot.rs
- shapely-json/src/from_json.rs
- shapely-json/src/tests.rs
- shapely-json/src/to_json.rs
- shapely-pretty/src/printer.rs
> feat: Proper HashMap support

- shapely-core/src/impls/hashmap_impl.rs
- shapely-core/src/impls/vec_impl.rs
- shapely-core/src/lib.rs
- shapely-core/src/mini_typeid.rs
- shapely-core/src/partial.rs
- shapely-core/src/scalar_contents.rs
- shapely-core/src/scalar_contents/tests.rs
- shapely-core/src/shape.rs
- shapely-core/src/shape/enum_shape.rs
- shapely-core/src/shape/list_shape.rs
- shapely-core/src/shape/map_shape.rs
- shapely-core/src/shape/pretty_print.rs
- shapely-core/src/shape/scalar_shape.rs
- shapely-core/src/slot.rs
- shapely-derive/src/lib.rs
- shapely-json/src/from_json.rs
- shapely-json/src/lib.rs
- shapely-json/src/to_json.rs
- shapely-pretty/src/lib.rs
- shapely-pretty/src/printer.rs
- shapely-urlencoded/src/lib.rs
- shapely-yaml/src/lib.rs
- shapely/README.md
- shapely/src/lib.rs
This adds warn(missing_docs) for all crates, and adds doc comments everywhere. Some of them are trivial. It's not great writing.. yet.
> Improve docs

- facet-codegen/src/tuples_impls.rs.j2
- facet-derive/src/lib.rs
- facet-derive/src/process_enum.rs
- facet-derive/src/process_struct.rs
- facet-derive/src/process_tuple_struct.rs
- facet-json-read/src/deserialize.rs
- facet-poke/src/map.rs
- facet-trait/src/impls/array_impl.rs
- facet-trait/src/impls/hashmap_impl.rs
- facet-trait/src/impls/scalar_impls.rs
- facet-trait/src/impls/slice_impl.rs
- facet-trait/src/impls/tuples_impls.rs
- facet-trait/src/impls/vec_impl.rs
- facet-trait/src/macros.rs
- facet-types/src/lib.rs
> WIP: make types non-exhaustive

- README.md
- facet/README.md
- facet/templates/README.md.j2
- templates/README.md.j2
> Fix typo in README: shaep -> shape

- Cargo.lock
- Cargo.toml
- README.md
- facet-args/Cargo.toml
- facet-args/README.md
- facet-args/src/lib.rs
- facet-args/templates/README.md.j2
- facet-args/tests/simple.rs
- facet-derive/src/lib.rs
- facet-derive/src/process_struct.rs
- facet-poke/src/lib.rs
- facet-poke/src/struct_.rs
- facet-poke/src/value.rs
- facet-samplelibc/build.rs
- facet-trait/src/impls/scalar_impls.rs
- facet-trait/src/macros.rs
- facet-types/src/lib.rs
- facet/README.md
- facet/templates/README.md.j2
- templates/README.md.j2
To show off a clap replacement
> WIP: facet-args

- Cargo.lock
- Cargo.toml
- facet-toml/Cargo.toml
- facet-toml/README.md
- facet-toml/src/lib.rs
- facet-toml/src/tests.rs
- facet-toml/templates/README.md.j2
> Toml fixup

- .github/workflows/test.yml
- Justfile
Just trying it out because damn, we're spending all our time downloading it :(
> Miri in container

- facet-poke/src/struct_.rs
- facet-poke/tests/poke_test.rs
This is starting to address the safety concerns brought up in #70
> Make set_field_by_name unchecked and marked as unsafe

- facet-core/src/types/mod.rs
> Implement Facet for some of facet-core's types

- .gitignore
- Cargo.lock
- facet-core/src/_trait/macros.rs
- facet-derive/src/lib.rs
- facet-derive/src/process_enum.rs
- facet-peek/src/enum_.rs
- facet-peek/src/lib.rs
- facet-poke/Cargo.toml
- facet-poke/src/enum_.rs
- facet-poke/tests/poke_test.rs
- facet-pretty/src/printer.rs
Enum support is currently half-baked. This is my attempt to add support for it on the peek and poke side.
> More enum support

- .github/workflows/test.yml
- Justfile
- sample/Cargo.lock
> Run a single test pipeline on self-hosted runner

- .github/workflows/test.yml
- Dockerfile
- Justfile
> Add Dockerfile

- .github/workflows/test.yml
- Dockerfile
- Justfile
Leaner images, separate for test & miri
> Custom img pt. 2

- facet-peek/Cargo.toml
- facet-poke/Cargo.toml
- facet/Cargo.toml
This is a follow up to #123, building on e0e1b8d
> fix: Ensure 'std' isn't enabled in no_std

- facet-core/src/_trait/impls/scalar_impls.rs
- facet-derive/src/lib.rs
- facet-derive/src/process_enum.rs
- facet-derive/src/process_struct.rs
- facet/src/sample_generated_code.rs
- facet/tests/derive.rs
Closes https://github.com/facet-rs/facet/issues/69
> feat(facet-derive): Support generic ADTs

- Justfile
- facet-codegen/src/main.rs
- facet-codegen/src/readmes.rs
- facet-derive/src/lib.rs
- facet-derive/src/process_enum.rs
- facet-derive/src/process_struct.rs
- facet/src/sample_generated_code.rs
1. Only write files if their contents changed
2. Target `::facet`, not `facet`.
Closes  #160
> Clean code generation

- facet-reflect/src/poke/enum_.rs
- facet-toml/src/error.rs
- facet-toml/src/lib.rs
- facet-toml/src/to_scalar.rs
- facet-toml/tests/enum_.rs
- facet-toml/tests/struct_.rs
I also added the `PokeEnumNoVarient::variant_by_name` and  `PokeEnumNoVarient::contains_variant_with_name` methods to make life a bit easier.
> TOML enum with unit variant implementation

- Cargo.lock
- facet-ansi/Cargo.toml
- facet-ansi/src/lib.rs
- facet-reflect/tests/poke/facts.rs
- facet-testhelpers/src/lib.rs
Closes #164, thanks @epage for the tip
> Use anstyle

- .envrc
- .github/workflows/test.yml
- Justfile
> Test output groupping

- facet-json/src/deserialize.rs
- facet-reflect/src/lib.rs
- facet-reflect/src/peek/value.rs
- facet-reflect/src/poke/value.rs
- facet-reflect/src/scalar.rs
- facet-yaml/src/lib.rs
I hope this is what you had in mind.
I removed all `NonZero` and `(i|u)128` variants.
> feat(reflect): add `ScalarType` enum

- facet-core/README.md
- facet-core/README.md.in
> Fix minor typo

- facet-codegen/src/main.rs
- facet-core/src/types/characteristic.rs
- facet-core/src/types/enum_.rs
- facet-core/src/types/field.rs
- facet-core/src/types/list.rs
- facet-core/src/types/map.rs
- facet-core/src/types/mod.rs
- facet-core/src/types/option.rs
- facet-core/src/types/scalar.rs
- facet-core/src/types/smart_pointer.rs
- facet-core/src/types/struct_.rs
> Split facet-core/types into multiple modules, prepare for Arc<T> etc.

- facet-core/src/_trait/impls/btree_impl.rs
- facet-core/src/_trait/impls/hashmap_impl.rs
- facet-core/src/_trait/impls/mod.rs
- sample/Cargo.toml
Implementation based on the one for HashMap.
Not sure where to add tests. 🤔
> Implement Facet for BTreeMap + minor simplifications for HashMap

- facet-core/Cargo.toml
- facet-reflect/Cargo.toml
- facet-toml/src/to_scalar.rs
- facet/Cargo.toml
This is just some minor cleanup for things I noticed when I was looking to make a change.
> fix(reflect): Hide the 'indexmap' feature

- README.md
- facet-codegen/src/gen_tuple_impl.rs
- facet-codegen/src/readmes.rs
- facet-core/src/impls_core/tuple.rs
- facet-core/src/types/field.rs
- facet-derive/src/lib.rs
- facet-reflect/src/peek/enum_.rs
- facet-reflect/src/peek/struct_.rs
- facet-reflect/src/wip/mod.rs
- facet/src/sample_generated_code.rs
- facet/tests/cycle.rs
- facet/tests/derive.rs
> Allow implementing Facet on recursive/cyclic types

- Cargo.lock
- facet-json/Cargo.toml
- facet-json/src/deserialize.rs
- facet-json/tests/json-read.rs
We'll want SIMD stuff, https://github.com/nst/JSONTestSuite etc. eventually — for now it's just about restoring previous functionality and taking the `Wip` API through its paces.
> Naive and very limited JSON parser

- Cargo.lock
- facet-toml/Cargo.toml
- facet-toml/src/lib.rs
- facet-toml/tests/basic.rs
- facet-toml/tests/enum_.rs
- facet-toml/tests/scalar.rs
- facet-toml/tests/struct_.rs
Not everything is covered yet, which I will add later.
> Deserialize enum in TOML

- Cargo.lock
- facet-dev/Cargo.toml
- facet-dev/src/main.rs
And solve the first security advisory for facet oh gosh!
(good thing nobody filed a thousand for all the unsoundness early on..)
> Remove unecessary dependencies on atty/console

- facet-toml/src/lib.rs
- facet-toml/tests/list.rs
- facet-toml/tests/map.rs
I'm quite busy these days, so my progress is a bit slow. But at least there is still progress :)
> fix(toml): implement list and map parsing

- facet-core/src/types/mod.rs
> Define PartialEq manually

- facet-derive-emit/src/process_enum.rs
- facet-derive-emit/tests/snapshots/codegen__array_field_in_enum.snap
- facet-derive-emit/tests/snapshots/codegen__enum_doc_comment.snap
- facet-derive-emit/tests/snapshots/codegen__enum_generic.snap
- facet-derive-emit/tests/snapshots/codegen__enum_variants_with_comments.snap
- facet-derive-emit/tests/snapshots/codegen__enum_with_facet_attributes.snap
- facet-derive-emit/tests/snapshots/codegen__enum_with_nested_generic_in_variant_one_level.snap
- facet-derive-emit/tests/snapshots/codegen__enum_with_nested_generic_in_variant_two_levels.snap
- facet-derive-emit/tests/snapshots/codegen__enum_with_variants.snap
- facet/src/sample_generated_code.rs
- sample/Cargo.lock
- Solves #266 (which was causing confusion when working on #256)
> fix(facet-derive-emit): extract variant array binding to reduce nesting for rustfmt

- facet-derive-emit/tests/codegen.rs
- facet-derive-emit/tests/snapshots/codegen__repr_c_enum.snap
> Add test for repr(C) enum

- facet-derive-emit/src/lib.rs
- facet-derive-emit/src/process_enum.rs
- facet-derive-emit/tests/codegen.rs
- facet-derive-emit/tests/snapshots/codegen__enum_with_discriminants_binary.snap
- facet-derive-emit/tests/snapshots/codegen__enum_with_discriminants_decimal.snap
- facet-derive-emit/tests/snapshots/codegen__enum_with_discriminants_hexadecimal.snap
- facet-derive-emit/tests/snapshots/codegen__enum_with_discriminants_mixed_notations.snap
- facet-derive-parse/src/lib.rs
> Support hex literals in enum discriminants

- facet-core/src/types/mod.rs
- facet-derive-emit/src/lib.rs
- facet-derive-emit/src/process_struct.rs
- facet-derive-parse/src/lib.rs
- facet-json/src/deserialize.rs
- facet-json/src/deserialize/error.rs
- facet-json/tests/integration/err.rs
- facet-json/tests/integration/read.rs
- facet-reflect/Cargo.toml
- facet-reflect/src/lib.rs
- facet-reflect/src/wip/enum_.rs
- facet-reflect/src/wip/heap_value.rs
- facet-reflect/src/wip/mod.rs
feat(json) Support deny_unknown_fields
Closes #288
This also makes the `log` feature of `facet-reflect` optional, and introduces shape attributes.
> feat(json) deny unknown fields

- facet-json/src/deserialize.rs
- facet-json/src/deserialize/error.rs
- facet-json/tests/integration/read.rs
- facet-json/tests/integration/snapshots/r#mod__integration__read__field_rename_missing_required_error.snap
- facet-reflect/src/wip/mod.rs
> feat(json) Better error messages when a field is missing

- facet-json/src/serialize.rs
- facet-json/tests/integration/read.rs
- facet-json/tests/integration/read/tuple.rs
- facet-json/tests/integration/read/vec.rs
- facet-json/tests/integration/write.rs
> Make tuples serialize into lists rather than objects

- Cargo.lock
- facet-derive-emit/Cargo.toml
- facet-derive-emit/tests/compile_tests.rs
- facet-derive-emit/tests/mod.rs
- facet-dev/src/main.rs
- facet-reflect/src/wip/mod.rs
- facet-reflect/tests/peek/facts.rs
- facet-reflect/tests/wip/compile_tests.rs
- outside-workspace/sample-c-lib-user/src/main.rs
This code was elegantly nicked from `facet-reflect`
> Actually run compile test for skip_serializing_if

- Cargo.lock
- facet-toml/Cargo.toml
- facet-toml/src/error.rs
- facet-toml/src/lib.rs
- facet-toml/src/to_scalar.rs
- facet-toml/tests/document.rs
- facet-toml/tests/enum_.rs
- facet-toml/tests/list.rs
- facet-toml/tests/map.rs
- facet-toml/tests/option.rs
- facet-toml/tests/scalar.rs
- facet-toml/tests/struct_.rs
Sorry for being inactive for a few days! I'm also currently working on adding proper error handling with ariadne similar to the JSON crate.
> feat(toml): pretty error reports & enum fix

- facet-json/src/deserialize.rs
- facet-json/src/deserialize/error.rs
- facet-json/tests/integration/read.rs
- facet-json/tests/integration/read/enums.rs
Without support for rename, so far.
> Implement naive JSON variant (unit variants)

- Cargo.lock
- facet-core/Cargo.toml
- facet-dev/Cargo.toml
- facet-yaml/Cargo.toml
Not sure how frequent you want these types of commits.
> chore(deps): update dependencies

- .github/renovate.json
I think this is a good foundation, to be extended further later.
> chore(renovate): group non-major renovate PRs

- Cargo.lock
- facet-core/Cargo.toml
- facet-core/src/impls_ordered_float.rs
- facet-core/src/lib.rs
- facet-json/Cargo.toml
- facet-json/src/deserialize.rs
- facet-json/tests/integration/transparent.rs
> feat: Add support for ordered-float

- Cargo.lock
- facet-jsonschema/Cargo.toml
> fix: jsonschema doctest breakage

- Cargo.toml
- facet-args/Cargo.toml
- facet-core/Cargo.toml
- facet-derive-emit/Cargo.toml
- facet-derive-parse/Cargo.toml
- facet-derive/Cargo.toml
- facet-dev/Cargo.toml
- facet-json/Cargo.toml
- facet-jsonschema/Cargo.toml
- facet-kdl/Cargo.toml
- facet-msgpack/Cargo.toml
- facet-pretty/Cargo.toml
- facet-reflect/Cargo.toml
- facet-testhelpers/Cargo.toml
- facet-toml/Cargo.toml
- facet-urlencoded/Cargo.toml
- facet-yaml/Cargo.toml
- facet/Cargo.toml
> Remove all authors

- Cargo.lock
- facet-jsonschema/Cargo.toml
- facet-jsonschema/src/lib.rs
- facet-jsonschema/src/snapshots/facet_jsonschema__tests__basic.snap
> Depend on insta rather than schemars+syn

- Cargo.lock
- Justfile
- facet-core/Cargo.toml
- facet-core/src/impls_ulid.rs
- facet-core/src/lib.rs
- facet-core/src/types/scalar.rs
- facet-json/Cargo.toml
- facet-json/tests/integration/transparent.rs
- facet-yaml/Cargo.toml
- facet-yaml/tests/from_str.rs
- **Add ulid support**
- **Drop msrv from prepush**
> Add support for ulid crate

- .github/workflows/test.yml
- Cargo.lock
- Justfile
- facet-core/Cargo.toml
- facet-core/src/impls_alloc/smartptr.rs
- facet-core/src/types/mod.rs
- facet-json/tests/integration/err.rs
- facet-json/tests/integration/read/deny_unknown_and_default.rs
- facet-json/tests/integration/read/nonzero.rs
- facet-json/tests/integration/read/rename.rs
- facet-reflect/src/wip/mod.rs
- facet-reflect/tests/wip/map.rs
- facet-reflect/tests/wip/misc.rs
- facet-yaml/tests/from_str.rs
> Plug more leaks, cf. #354

- facet-json/tests/integration/read/rename.rs
- facet-reflect/src/wip/mod.rs
Without this change the new test fails.
> fix(reflect): make rename an actual rename instead of an alias

- facet-json/tests/integration/read/bool.rs
- facet-json/tests/integration/read/deny_unknown_and_default.rs
- facet-json/tests/integration/read/enums.rs
- facet-json/tests/integration/read/eof_and_nulls.rs
- facet-json/tests/integration/read/hashmap.rs
- facet-json/tests/integration/read/numbers.rs
- facet-json/tests/integration/read/option.rs
- facet-json/tests/integration/read/primitives.rs
- facet-json/tests/integration/read/rename.rs
- facet-json/tests/integration/read/skip_unknown_fields.rs
- facet-json/tests/integration/read/structs.rs
- facet-json/tests/integration/read/tuple.rs
- facet-json/tests/integration/read/vec.rs
- facet-json/tests/integration/write/json.rs
As per this comment: https://github.com/facet-rs/facet/pull/403#discussion_r2061205232
> test(json): use eyre::Result for better errors

- .envrc
- docs/.gitignore
- docs/content/_index.md
- docs/package.json
- docs/pnpm-lock.yaml
> Fix trailing better assert sentence

- facet-json/src/lib.rs
- facet-json/src/serialize.rs
Not sure if this is an improvement but it was fun
> add First trait

- facet-args/README.md
- facet-args/README.md.in
- facet-args/src/lib.rs
- facet-args/tests/simple.rs
Fixes: https://github.com/facet-rs/facet/issues/443
> Resolve #443 - handle short named argument

- facet-toml/src/lib.rs
- facet-toml/tests/struct_.rs
Also add some tests for the `rename` and `rename_all` attributes.
> feat(toml): implement 'default' attribute

- facet-core/src/types/enum_.rs
- facet-derive-emit/src/process_enum.rs
- facet-derive-emit/tests/codegen/snapshots/r#mod__codegen__array_field_in_enum.snap
- facet-derive-emit/tests/codegen/snapshots/r#mod__codegen__enum_doc_comment.snap
- facet-derive-emit/tests/codegen/snapshots/r#mod__codegen__enum_generic.snap
- facet-derive-emit/tests/codegen/snapshots/r#mod__codegen__enum_variants_with_comments.snap
- facet-derive-emit/tests/codegen/snapshots/r#mod__codegen__enum_with_discriminants_binary.snap
- facet-derive-emit/tests/codegen/snapshots/r#mod__codegen__enum_with_discriminants_decimal.snap
- facet-derive-emit/tests/codegen/snapshots/r#mod__codegen__enum_with_discriminants_hexadecimal.snap
- facet-derive-emit/tests/codegen/snapshots/r#mod__codegen__enum_with_discriminants_mixed_notations.snap
- facet-derive-emit/tests/codegen/snapshots/r#mod__codegen__enum_with_facet_attributes.snap
- facet-derive-emit/tests/codegen/snapshots/r#mod__codegen__enum_with_multiple_attributes_per_variant.snap
- facet-derive-emit/tests/codegen/snapshots/r#mod__codegen__enum_with_nested_generic_in_variant_one_level.snap
- facet-derive-emit/tests/codegen/snapshots/r#mod__codegen__enum_with_nested_generic_in_variant_two_levels.snap
- facet-derive-emit/tests/codegen/snapshots/r#mod__codegen__enum_with_rename_all.snap
- facet-derive-emit/tests/codegen/snapshots/r#mod__codegen__enum_with_renamed_variants_and_fields.snap
- facet-derive-emit/tests/codegen/snapshots/r#mod__codegen__enum_with_variants.snap
- facet-derive-emit/tests/codegen/snapshots/r#mod__codegen__repr_c_enum.snap
- facet/src/sample_generated_code.rs
I've resolved the conflicts with #452 — should be good to go.
> Add support for rename_all and arbitrary attributes on variants (rebased #461)

- Cargo.lock
- facet-json/Cargo.toml
- facet-json/benches/compare_serde.rs
- facet-pretty/Cargo.toml
- facet-pretty/benches/compare_derive_more.rs
> Add benchmarks

- facet-core/src/spez/mod.rs
- facet-reflect/tests/wip/misc.rs
> Fix clone_into functions

- facet-core/src/impls_alloc/btreemap.rs
- facet-core/src/impls_alloc/vec.rs
- facet-core/src/impls_std/hashmap.rs
- facet-reflect/tests/wip/misc.rs
> Fix clone_into for collections

- Cargo.lock
- facet-reflect/Cargo.toml
- facet-reflect/src/scalar.rs
- facet-serialize/src/lib.rs
- facet-toml/src/deserialize/mod.rs
- facet-toml/src/deserialize/to_scalar.rs
- facet-toml/tests/deserialize/scalar.rs
Nothing fancy, I just thought this would read better.
> fix(reflect): add missing scalar types

- facet-yaml/Cargo.toml
- facet-yaml/src/deserialize/error.rs
- facet-yaml/src/deserialize/mod.rs
- facet-yaml/src/lib.rs
- facet-yaml/src/serialize/error.rs
- facet-yaml/src/serialize/mod.rs
Not sure if I want to commit to that, but this at least prepares the structure for someone to pick it up.
> refactor(yaml): prepare for serialization implementation

- facet-core/src/impls_alloc/vec.rs
- facet-core/src/impls_core/array.rs
- facet-core/src/impls_core/slice.rs
- facet-core/src/types/def/array.rs
- facet-core/src/types/def/list.rs
- facet-core/src/types/def/slice.rs
- facet-deserialize/src/lib.rs
- facet-json/tests/array_test.rs
- facet-reflect/src/error.rs
- facet-reflect/src/wip/drop.rs
- facet-reflect/src/wip/frame.rs
- facet-reflect/src/wip/mod.rs
- facet-reflect/src/wip/pop.rs
- facet-reflect/tests/wip/array_building.rs
- facet-reflect/tests/wip/mod.rs
- facet-reflect/tests/wip/no_uninit.rs
Add support for partially initializing arrays, closes #504
> facet-reflect + facet-json: Handle arrays

- facet-derive-emit/src/derive.rs
- facet-derive-emit/src/parsed.rs
- facet-derive-emit/src/process_enum.rs
- facet-derive-emit/tests/codegen/mod.rs
- facet-derive-emit/tests/codegen/snapshots/r#mod__codegen__array_field_in_enum.snap
- facet-derive-emit/tests/codegen/snapshots/r#mod__codegen__enum_generic.snap
- facet-derive-emit/tests/codegen/snapshots/r#mod__codegen__enum_variants_with_comments.snap
- facet-derive-emit/tests/codegen/snapshots/r#mod__codegen__enum_with_discriminants_binary.snap
- facet-derive-emit/tests/codegen/snapshots/r#mod__codegen__enum_with_discriminants_decimal.snap
- facet-derive-emit/tests/codegen/snapshots/r#mod__codegen__enum_with_discriminants_hexadecimal.snap
- facet-derive-emit/tests/codegen/snapshots/r#mod__codegen__enum_with_discriminants_mixed_notations.snap
- facet-derive-emit/tests/codegen/snapshots/r#mod__codegen__enum_with_facet_attributes.snap
- facet-derive-emit/tests/codegen/snapshots/r#mod__codegen__enum_with_macro_discriminants.snap
- facet-derive-emit/tests/codegen/snapshots/r#mod__codegen__enum_with_multiple_attributes_per_variant.snap
- facet-derive-emit/tests/codegen/snapshots/r#mod__codegen__enum_with_nested_generic_in_variant_one_level.snap
- facet-derive-emit/tests/codegen/snapshots/r#mod__codegen__enum_with_nested_generic_in_variant_two_levels.snap
- facet-derive-emit/tests/codegen/snapshots/r#mod__codegen__enum_with_rename_all.snap
- facet-derive-emit/tests/codegen/snapshots/r#mod__codegen__enum_with_renamed_variants_and_fields.snap
- facet-derive-emit/tests/codegen/snapshots/r#mod__codegen__enum_with_variants.snap
- facet-derive-emit/tests/codegen/snapshots/r#mod__codegen__repr_c_enum.snap
- facet-derive-emit/tests/codegen/snapshots/r#mod__codegen__repr_c_enum_empty_struct_variant.snap
- facet-derive-emit/tests/codegen/snapshots/r#mod__codegen__repr_c_enum_lifetime_field.snap
- facet-derive-emit/tests/compile_tests/macro_discriminant.rs
- facet-derive-parse/src/lib.rs
- facet/src/sample_generated_code.rs
> Allow macros in enum discriminants

- facet-derive-emit/src/process_struct.rs
- facet-derive-emit/tests/codegen/mod.rs
- facet-derive-emit/tests/codegen/snapshots/r#mod__codegen__struct_with_option_cow_str.snap
- facet-derive-parse/src/lib.rs
- facet/tests/derive.rs
...by replacing the lifetime with 'static for the
static assertion.
Closes #576
> Make default fields with a lifetime work

- Cargo.lock
- Cargo.toml
- facet-xdr/CHANGELOG.md
- facet-xdr/Cargo.toml
- facet-xdr/README.md
- facet-xdr/README.md.in
- facet-xdr/src/lib.rs
- facet-xdr/tests/mod.rs
I did some proptesting [out of tree](https://github.com/RoastVeg/facet-xdr/blob/79246b311e13923de2294ffbb29a2e7b7f882a21/src/lib.rs#L802) while I was making this, but since proptest is full of syn I figured it wasn't worth porting over.
> Add facet-xdr

- Justfile
- facet-core/src/impls_alloc/arc.rs
- facet-core/src/impls_alloc/boxed.rs
- facet-core/src/impls_alloc/rc.rs
- facet-core/src/impls_camino.rs
- facet-core/src/impls_core/option.rs
- facet-core/src/impls_core/scalar.rs
- facet-core/src/impls_jiff.rs
- facet-core/src/impls_ordered_float.rs
- facet-core/src/impls_ulid.rs
- facet-core/src/impls_url.rs
- facet-core/src/impls_uuid.rs
- facet-core/src/ptr.rs
- facet-core/src/spez/mod.rs
- facet-core/src/types/def/smartptr.rs
- facet-core/src/types/value.rs
- facet-derive-emit/src/process_struct.rs
- facet-derive-emit/tests/codegen/mod.rs
- facet-derive-emit/tests/codegen/snapshots/r#mod__codegen__pub_crate_enum.snap
- facet-derive-emit/tests/codegen/snapshots/r#mod__codegen__pub_crate_sigh.snap
- facet-derive-emit/tests/codegen/snapshots/r#mod__codegen__struct_facet_transparent.snap
- facet-derive-parse/src/lib.rs
Some of the code is still sus, but this works for the basic case / existing tests run. I think TryFrom is wrong.
> Support Arc<T> where T: ?Sized

- facet-core/src/impls_alloc/btreemap.rs
- facet-core/src/impls_std/hashmap.rs
- facet-core/src/types/def/map.rs
- facet-reflect/src/peek/map.rs
Taken from #496 at @ThouCheese's request.
> Allow iterating maps in reverse order

- Cargo.lock
- facet-core/src/types/ty/pointer.rs
- facet-pretty/Cargo.toml
- facet-pretty/examples/basic_usage.rs
- facet-pretty/src/printer.rs
- facet-pretty/tests/pretty_print.rs
- facet-pretty/tests/snapshots/pretty_print__byte_slice.snap
- facet-pretty/tests/snapshots/pretty_print__str.snap
- facet-pretty/tests/snapshots/pretty_print__u32_slice.snap
- facet-pretty/tests/snapshots/pretty_print__vec_u32.snap
- facet-pretty/tests/snapshots/pretty_print__vec_u8.snap
- facet-reflect/src/peek/value.rs
> Support &str slices in facet-pretty

- facet-json/src/iterative/serialize.rs
- facet-json/src/lib.rs
- facet-json/src/recursive/serialize.rs
- facet-reflect/src/peek/enum_.rs
- facet-reflect/src/peek/struct_.rs
- facet-reflect/src/peek/value.rs
- facet-reflect/tests/compile_tests.rs
- facet-reflect/tests/peek/compile_tests/contravariant_shrinking.rs
- facet-reflect/tests/peek/compile_tests/covariant_growing.rs
- facet-reflect/tests/peek/compile_tests/invariant_growing.rs
- facet-reflect/tests/peek/compile_tests/invariant_shrinking.rs
- facet-reflect/tests/wip/mod.rs
- facet-serialize/src/lib.rs
> Remove nonsensical trait bound

- facet-core/src/types/def/iter.rs
- facet-core/src/types/def/list.rs
- facet-core/src/types/mod.rs
- facet-reflect/src/peek/list_like.rs
Fix problems mentioned in #701.
> Solve code comment inconsistencies and add missing validations

- facet-derive-emit/src/process_enum.rs
- facet-derive-emit/tests/codegen/snapshots/r#mod__codegen__array_field_in_enum.snap
- facet-derive-emit/tests/codegen/snapshots/r#mod__codegen__enum_doc_comment.snap
- facet-derive-emit/tests/codegen/snapshots/r#mod__codegen__enum_generic.snap
- facet-derive-emit/tests/codegen/snapshots/r#mod__codegen__enum_variants_with_comments.snap
- facet-derive-emit/tests/codegen/snapshots/r#mod__codegen__enum_with_discriminants_binary.snap
- facet-derive-emit/tests/codegen/snapshots/r#mod__codegen__enum_with_discriminants_decimal.snap
- facet-derive-emit/tests/codegen/snapshots/r#mod__codegen__enum_with_discriminants_hexadecimal.snap
- facet-derive-emit/tests/codegen/snapshots/r#mod__codegen__enum_with_discriminants_mixed_notations.snap
- facet-derive-emit/tests/codegen/snapshots/r#mod__codegen__enum_with_facet_attributes.snap
- facet-derive-emit/tests/codegen/snapshots/r#mod__codegen__enum_with_macro_discriminants.snap
- facet-derive-emit/tests/codegen/snapshots/r#mod__codegen__enum_with_multiple_attributes_per_variant.snap
- facet-derive-emit/tests/codegen/snapshots/r#mod__codegen__enum_with_nested_generic_in_variant_one_level.snap
- facet-derive-emit/tests/codegen/snapshots/r#mod__codegen__enum_with_nested_generic_in_variant_two_levels.snap
- facet-derive-emit/tests/codegen/snapshots/r#mod__codegen__enum_with_rename_all.snap
- facet-derive-emit/tests/codegen/snapshots/r#mod__codegen__enum_with_renamed_variants_and_fields.snap
- facet-derive-emit/tests/codegen/snapshots/r#mod__codegen__enum_with_variants.snap
- facet-derive-emit/tests/codegen/snapshots/r#mod__codegen__pub_crate_enum.snap
- facet-derive-emit/tests/codegen/snapshots/r#mod__codegen__repr_c_enum.snap
- facet-derive-emit/tests/codegen/snapshots/r#mod__codegen__repr_c_enum_empty_struct_variant.snap
- facet-derive-emit/tests/codegen/snapshots/r#mod__codegen__repr_c_enum_lifetime_field.snap
- facet/src/sample_generated_code.rs
- facet/tests/derive.rs
> Fix derive on enums with a non-i64 discriminant

- facet-toml/src/deserialize/mod.rs
- facet-toml/src/serialize/array_of_tables.rs
- facet-toml/src/serialize/error.rs
- facet-toml/src/serialize/mod.rs
- facet-toml/tests/serialize/mod.rs
- facet-toml/tests/serialize/vec_struct.rs
- facet-toml/tests/vec_array_of_tables.rs
> Support (de)serializing arrays of tables

- facet-toml/src/serialize/mod.rs
It feels strange to have functions take arguments that are only used in debug contexts, and have no potential for future use. This commit removes the `type_name` argument from `push_key` and `pop_key`. This argument had a misleading name to begin with.
Instead, the traces are moved to a position that has all of the required context; there is no further need to pass around static strings for debugging purposes, keeping business logic clean.
> facet-toml: ser: TomlSerializer: move traces to avoid debug-only args

- flake.nix
- shell.nix
This is my attempt to tidy up the flake a little more. These are opinions, but popular ones (within my circle at least).
> flake: stylistic improvements

- docs/content/_index.md
> fix simple typo in _index.html

- facet-core/src/ptr.rs
- facet-reflect/src/partial/mod.rs
- facet-reflect/src/peek/enum_.rs
- facet-reflect/src/peek/fields.rs
- facet-reflect/src/peek/list.rs
- facet-reflect/src/peek/list_like.rs
- facet-reflect/src/peek/map.rs
- facet-reflect/src/peek/option.rs
- facet-reflect/src/peek/smartptr.rs
- facet-reflect/src/peek/value.rs
- facet-reflect/tests/peek/facts.rs
- facet-reflect/tests/peek/value.rs
> Introduce GenericPtr

- Justfile
> Don't run all of facet-json under miri (in fact, don't run any of it)

- facet-core/src/types/value.rs
Closes https://github.com/facet-rs/facet/issues/631
> Document limited Send/Sync detection abilities

- Cargo.lock
- facet-json/Cargo.toml
- facet-json/src/tokenizer.rs
...by avoiding calls to .contains()
> Optimize parse_number
